# Site settings
title: wedy.chainy
email: askwedi@wedipedia.org
description: > # this means to ignore newlines until "baseurl:"
  Hello my name is Wedy Chainy and I am a software developer (mostly in web based apps), who write code in open source programming languages, I spend mostly my time living in terminal with my vim and fuelled by coffee.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wedy.github.io" # the base hostname & protocol for your site
github_username:  wedy
linkedin_username:  wchainy

# Build settings
markdown: kramdown
